### ISSUE TITLE
Issue with pickle/cpickle?

### ISSUE THREAD

**Issue by jparchure** [stitchfix/nodebook#2]
Hello, I just found out about Nodebook and was trying it out on my own machine.
However, when I follow the instructions, it gives me this module error on the first step, i.e while loading nodebook-

ModuleNotFoundError: No module named 'cPickle'
I am on Python 3.6 (MacOS Sierra), with Anaconda at 4.3.1
Any thoughts?

**Comment by kzielnicki** [comment]
Hi! Unfortunately Nodebook doesn't yet support Python 3, can you try running in Python 2.7? I plan to add Python 3 support in a future release.

**Comment by jparchure** [comment]
Will try that. Thanks
