### ISSUE TITLE
Failed to build nodebook

### ISSUE THREAD

**Issue by brylie** [stitchfix/nodebook#3]
While trying to install Nodebook in a Conda environment (Python 3.6), I get an error:

```
Failed to build nodebook
```

And the following traceback in JupyterLab:

```py
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-f93305de28c2> in <module>()
      1 #pragma nodebook off
      2 # here we load the nodebook extension and initialize the nodebook
----> 3 get_ipython().magic('load_ext nodebookext')
      4 get_ipython().magic('nodebook memory test_nb')
```

How do I properly install Nodebook in a conda environment with Python 3.6?

**Comment by kzielnicki** [comment]
Unfortunately Nodebook doesn't yet support Python 3, can you try running in Python 2.7? I plan to add Python 3 support in a future release.

**Comment by brylie** [comment]
OK, thanks. Pretty much all of my work in Python, so far, uses 3.x.

Is there an issue to track Python 3 support in nodebook?

**Comment by kzielnicki** [comment]
Just created this issue: https://github.com/stitchfix/nodebook/issues/4
